dist: trusty
language: node_js
node_js:
- 6

addons:
  apt:
    packages:
      - pulseaudio

env:
  global:
    - DISPLAY=:99.0
env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=firefox BVER=stable
    - env: BROWSER=firefox BVER=beta
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=beta
    - env: BROWSER=firefox BVER=nightly
    - env: BROWSER=firefox BVER=esr

before_install:
  - npm install -g npm@'>=3.0.0'

before_script:
  - npm install
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pulseaudio --start

script:
  - node_modules/.bin/grunt
  - npm test

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
